### ISSUE TITLE
Wrong version flag for some packages

### ISSUE THREAD

**Issue by unclechu** [tomchentw/gulp-livescript#26]
There's some dependencies in `package.json` which have `^` flag and major version less than `1`:
```
"vinyl-sourcemaps-apply": "^0.2.0"
...
"istanbul": "^0.4.1"
```
Are you sure about that? Because as I know major version as `0` means that developers could brake backward compatibility in next minor release, I think `~` flag will be preferable.

**Comment by tomchentw** [comment]
Please consult caret-range documentation [here](https://docs.npmjs.com/misc/semver#caret-ranges-1-2-3-0-2-5-0-0-4), I think it works the same way as `~` when version is `0.x`

**Comment by unclechu** [comment]
@tomchentw my mistake, thank you for making it clear for me!

**Comment by tomchentw** [comment]
Glad to help!
